

; PIC16F877A Configuration Bit Settings

; ASM source line config statements

#include "p16F877A.inc"

; CONFIG
; __config 0xFFF9
 __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _BOREN_ON & _LVP_ON & _CPD_OFF & _WRT_OFF & _CP_OFF


RES_VECT CODE 0x0000 
GOTO START 
MAIN_PROG CODE
 
START
    BSF STATUS,5     ;BANK 1 E GEC?S YAPILDI
    CLRF TRISD	    ; PORTD PINLERI CIKIS YAPIDLI 
    MOVLW 0xFF	    ; WORKE FF ATANDI
    MOVWF TRISB		; WORKTEN TRISE ATAMA YAPILARAK PORTB G?R?S OLARAK SEC?LD?
    BCF STATUS,5    	; BANK0'A GEC?S YAPILDI
 
BASLA
    MOVF PORTB,W	; PORTB B?LG?LER? WORKE ATILDI
    MOVWF PORTD	    ; WORKTEN PORTD YE YAZDIRILDI
    GOTO BASLA		; BASLA ET?KET?NE G?D?LD?
END

 